services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./config/qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__LOG_LEVEL=INFO

  face-rekon:
    build:
      context: .
      dockerfile: Dockerfile
    image: face-rekon
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - FLASK_DEBUG=false
      - FACE_REKON_USE_EMBEDDED_QDRANT=true
      - QDRANT_PATH=/config/face-rekon/qdrant
      - FACE_REKON_SIMILARITY_THRESHOLD=0.35
      - FACE_REKON_BORDERLINE_THRESHOLD=0.50
      - FACE_REKON_DEDUPLICATION_WINDOW=60
    volumes:
      - ./config:/config
      - ./tmp:/app/data/tmp # adjust as needed, depending on your local setup
      - ./scripts:/app/scripts
      - ./ui:/app/ui
      - ./tests:/app/tests # Mount tests directory for integration testing
    ports:
      - "5001:5001" # assuming Flask app runs on port 5001
