blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions & Discussions
    url: https://github.com/Rob-Negrete/ha-addons/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/Rob-Negrete/ha-addons/blob/main/README.md
    about: Read the documentation and user guides
  - name: 🚀 Home Assistant Community
    url: https://community.home-assistant.io/
    about: Get help from the Home Assistant community
